name: Archive release

on:
  workflow_dispatch:
  push:
    branches:
      - dev-browser
    tags:
      - 'latest'

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y upx-ucl
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Install dependencies (macOS/Windows)
      if: matrix.os != 'ubuntu-latest'
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build with PyInstaller
      run: python -m PyInstaller vai.spec

    - name: Archive PyInstaller output
      shell: bash
      run: |
        cd dist
        tar -czf ../vai-dist-${{ matrix.platform }}.tar.gz *
        cd ..

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: vai-dist-${{ matrix.platform }}
        path: vai-dist-${{ matrix.platform }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/tags/latest'
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          vai-dist-macos/*.tar.gz
          vai-dist-linux/*.tar.gz
          vai-dist-windows/*.tar.gz
        tag_name: latest
        name: Latest Release
        body: |
          This is the latest multi-platform build of the application.
          Built on: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}