name: Archive release

on:
  workflow_dispatch:
  push:
    branches:
      - dev-browser
    tags:
      - "latest"

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install additional dependencies for PyInstaller
        run: |
          sudo apt-get update
          sudo apt-get install -y upx-ucl

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller vai.spec

      - name: Archive dist folder
        run: tar -czf dist.tar.gz dist/

      - name: Delete existing 'latest' release
        if: github.ref == 'refs/tags/latest'
        run: |
          gh release delete latest --yes || true
          git push origin :latest || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create/Update Release
        if: github.ref == 'refs/tags/latest'
        uses: softprops/action-gh-release@v1
        with:
          files: dist.tar.gz
          tag_name: latest
          name: Latest Release
          body: |
            This is the latest build of the application.
            Built on: ${{ github.event.head_commit.timestamp }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact for dev-browser branch
        if: github.ref == 'refs/heads/dev-browser'
        uses: actions/upload-artifact@v3
        with:
          name: vai-dist
          path: dist.tar.gz

      - name: Create/Update latest tag
        if: github.ref == 'refs/heads/dev-browser'
        run: |
          git tag -f latest
          git push -f origin latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
