name: Cross-Platform Release

on:
  workflow_dispatch:
  push:
    branches:
      - dev-browser
    tags:
      - 'latest'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: macos-arm64 
            target_arch: arm64
    
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
      shell: bash

    - name: Install UPX (macOS)
      run: |
        brew install upx

    - name: Build with PyInstaller
      run: |
        ARCHFLAGS="-arch ${{ matrix.target_arch }}" python -m PyInstaller vai.spec
      shell: bash

    - name: Archive output
      run: |
        cd dist
        zip -r ../vai-${{ matrix.platform }}.zip *
      shell: bash

    - name: Upload artifacts
      if: github.ref == 'refs/heads/dev-browser'
      uses: actions/upload-artifact@v3
      with:
        name: vai-${{ matrix.platform }}
        path: vai-${{ matrix.platform }}.zip

    - name: Delete existing release
      if: github.ref == 'refs/tags/latest'
      run: |
        gh release delete latest --yes || true
        git push origin :latest || true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create/Update Release
      if: github.ref == 'refs/tags/latest'
      uses: softprops/action-gh-release@v1
      with:
        files: vai-${{ matrix.platform }}.zip
        tag_name: latest
        name: Latest Release
        body: |
          Latest build for ${{ matrix.platform }}
          Built on: ${{ github.event.head_commit.timestamp }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update latest tag
      if: github.ref == 'refs/heads/dev-browser'
      run: |
        git tag -f latest
        git push -f origin latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}